# Generated by Django 3.1.4 on 2020-12-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата поступления')),
                ('unit', models.CharField(max_length=128, verbose_name='Единица измерения')),
                ('vendor', models.CharField(max_length=128, verbose_name='Имя поставщика')),
            ],
        ),
    ]
