# Generated by Django 3.1.4 on 2020-12-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201226_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Цена'),
        ),
    ]
